### ISSUE TITLE
建立雲端數據分析之最佳實踐

### ISSUE THREAD

**Issue by jazzwang** [datacontw/DataCon.TW_2022#1]
* 演講主題 Talk Topic: `建立雲端數據分析之最佳實踐`
* 講者姓名 Name: `Shih-Yong Wang`
* 單位名稱 Organization & Job Title: `Mgr, Solutions Architect, Amazon Web Services`
* 講者簡介 Self Introduction:

> AWS 臺灣解決方案架構師，擁有二十年 IT 產業的相關工作經驗，目前負責協助各個規模及不同產業的客戶，透過使用 AWS 實現其商業價值，並且為創新帶來無限契機。

* 講題摘要 Abstract:

> 本章節描述了如和在 AWS 上優化已有的數據分析工作，藉由經過客戶驗證的用於設計架構完善的分析工作負載的最佳實踐。包含 AWS 從真實案例研究中收集的見解，可幫助您了解架構良好的分析工作負載的關鍵設計元素以及改進建議。適用於構建和操作分析系統的 IT 架構師、開發人員和團隊成員。

**Comment by raywang1021** [comment]
Speakers: 
Shih-Yong Wang, Mgr, Solutions Architect, Amazon Web Services
Ray Wang, Solutions Architect, Amazon Web Services
_And we want to change to pre-recording, is that work for you_ @jazzwang

**Comment by jazzwang** [comment]
> Shih-Yong Wang, Mgr, Solutions Architect, Amazon Web Services
> Ray Wang, Solutions Architect, Amazon Web Services

confirmed and added to Agenda
