### ISSUE TITLE
Reactive micro-pipeline platform for data-processing and ML

### ISSUE THREAD

**Issue by jazzwang** [datacontw/DataCon.TW_2022#4]
* 演講主題 Talk Topic: `響應式微服務的資料與模型排程工廠 (Reactive micro-pipeline platform for data-processing and ML)`
* 講者姓名 Name: `賴義偉`
* 單位名稱 Organization & Job Title: `國泰金控 DST 資料科學工程師`
* 講者簡介 Self Introduction:

![](https://www.facebook.com/photo/?fbid=2850370031645995&set=a.157281107621581)

> 做為一個資料科學工程師，目前在國泰金控服務，打造行內方便開發與建模的數據平台。在資料工程領域上，已經有了 8 年以上的經歷，曾經建置過 Hadoop 平台，用 Airflow 打造數據排程，使用 ELK 建立搜尋服務以及日誌收集系統。喜歡跨領域學習，結合各項知識與技能來幫助完成工作目標。

* 講題摘要 Abstract:

> 在國泰金控內，我們為了應付大量資料排程設計和維運，以及將資料應用在模型開發和訓練上，發展出一套不一樣的 Airflow 模式。主要是我們的設計概念，應用響應式理念為 Airflow 打造排程。過程中我們透過拆解資料流程，分成監聽和導入模式，以及讓排程工廠可以根據這兩個模式，模組化生出排程來進行資料和模型處理。讓 Airflow 可以像工廠一樣，生產出標準化的產品，讓我們能進行方便的使用和推廣。

**Comment by raix852** [comment]
補充講者介紹：
做為一個資料工程師，目前在國泰金控服務，打造行內方便開發與建模的數據平台。在資料工程領域上，已經有了 8 年以上的經歷，曾經建置過 Hadoop 平台，用 Airflow 打造數據排程，使用 ELK 建立搜尋服務以及日誌收集系統。喜歡跨領域學習，結合各項知識與技能來幫助完成工作目標。
