### ISSUE TITLE
Ray: The alternative to distributed frameworks

### ISSUE THREAD

**Issue by jazzwang** [datacontw/DataCon.TW_2022#5]
* 演講主題 Talk Topic: `Ray: The alternative to distributed frameworks`
* 講者姓名 Name: `李泓旻 Andrew Li`
* 單位名稱 Organization & Job Title: `資料工程師 / 國泰金控 Data Science & Technology`
* 講者簡介 Self Introduction:

<img src="https://drive.google.com/file/d/1uG7j3he8mA4g6HLrdWDaKfrZANeCVYvb/view?usp=sharing"/>

> I am currently working as a data engineer in the financial industry. In the past, I worked as a one-stop shop for data science(Manufacturing), covering data engineering, ETL, modeling, and deployment. Dedicated to finding the most suitable tool for each need. Keep contributing to open source projects.

* 講題摘要 Abstract:

> 1. 開場自介 [1 min]
> 2. 情境敘述 [5 min]
>    在資料科學開發過程中，Python 開發者可能會先使用小量資料進行 ETL 開發或是模型開發，接著當資料量成長到一個程度或是為了效能考量時，再交由資料工程師利用其他的分散式框架改寫。在快速迭代的開發過程中，造成開發飛輪轉動緩慢的原因，往往不是運算能力的限制，而是 re-write 成本、重新測試成本、以及溝通成本。因此，如果有一個「通用型的分散式框架」可以讓開發者同時應用於 ETL 與 Modeling 兩種情境，也可以讓開發者在維持在 laptop/workstation 上開發的習慣，但是當需要進行分散式運算時，僅需要修改簡單的 config 即可遷移至大型的運算叢集，如 Cloud、Kubernetes。以下分享兩個常見案例來說明。
> 3. Use Cases
>    3.1. Tuning with your favorite machine learning framework [7 min]
>    3.2. A drop-in replacement for pandas [7 min]
> 4. 簡介 Ray 的基礎架構與功能 [15 min]
> 5. Q&A [5 min]

**Comment by orcahmlee** [comment]
HI, @jazzwang 

補充講者簡介 Self Introduction:

> I am currently working as a data engineer in the financial industry. In the past, I worked as a one-stop shop for data science(Manufacturing), covering data engineering, ETL, modeling, and deployment. Dedicated to finding the most suitable tool for each need. Keep contributing to open source projects.
